# Generated by Django 5.2.12 on 2026-03-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='urinedata',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
